version: '3'

services:
  server1:
    build: ./server1  # Uses server1/Dockerfile
    container_name: server1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  server2:
    build: ./server2  # Uses server2/Dockerfile
    container_name: server2
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
